version: '3.0'
services:
  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=fred
    networks:
        vpcbr:
          ipv4_address: 10.5.0.5
  web:
    build: .
    ports:
     - "8080:8080"
    depends_on:
           - postgres
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=fred
     - POSTGRES_HOST=10.5.0.5
    networks:
        vpcbr:
          ipv4_address: 10.5.0.6

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16