version: '3.0'
services:
  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=fred
  web:
    build: .
    ports:
     - "8080:8080"
    depends_on:
           - postgres
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=fred
     - POSTGRES_HOST=postgres
